name: Run Postman Tests with HTML Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Newman tests
        run: |
          newman run postman/AutomationExercise.postman_collection.json \
            --environment postman/environment.json \
            --reporters cli,html \
            --reporter-html-export newman/report.html

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: postman-html-report
          path: newman/report.html
